### ISSUE TITLE
Contacts sync limit

### ISSUE THREAD

**Issue by bitimp** [hidespb/node-whatsapi#44]
Hi!

If I sync at one time more than 255 contacts - I see the error:

buffer.js:790
    throw new TypeError('value is out of bounds');
          ^
TypeError: value is out of bounds
    at checkInt (buffer.js:790:11)
    at Buffer.writeUInt8 (buffer.js:834:5)
    at Writer.writeInt8 (...\node_modules\whatsapi\protocol.js:803:14)
    at Writer.writeListStart (...\node_modules\whatsapi\protocol.js:709:7)
    at Writer.writeNode (...\node_modules\whatsapi\protocol.js:690:8)
    at Writer.<anonymous> (...\node_modules\whatsapi\protocol.js:693:9)
    at Array.forEach (native)
    at Writer.writeNode (...\node_modules\whatsapi\protocol.js:692:19)
    at Writer.node (...\node_modules\whatsapi\protocol.js:634:8)
    at WhatsApi.sendNode (...\node_modules\whatsapi\whatsapi.js:214:32)

The reasons for this error I understand.
Is it possible to somehow fix this limitation?

**Comment by matteocontrini** [comment]
I guess this is because numbers greater than 255 can't be represented with 8 bits (unsigned) and I read something about that in the stack trace.
@tvandergeer knows the magic that happens inside protocol.js better than me, so maybe he has an idea.

**Comment by matteocontrini** [comment]
Anyway, the best thing you can do is probably splitting the contacts in more batches and syncing them in delta mode.

**Comment by matteocontrini** [comment]
This 34d702a07f8479e14fe5d3d8153a6cf5174ee623 should fix it, can you check please?
